Add word list checks

diff --git a/Script/JWT_Crawler_Config_File b/Script/JWT_Crawler_Config_File
--- a/Script/JWT_Crawler_Config_File
+++ b/Script/JWT_Crawler_Config_File
@@ -14,7 +14,6 @@ printf "[*]     JWT_Crawler\n"
 printf "[*]     Fenrir\n\n"
 
 URL=""
-#TODO: add trailing / if not detected
 tok_gen_location=""
 username=""
 password=""
@@ -42,6 +41,22 @@ fi
 if [ ! ${URL:$((${#URL}-1)):1} == "/" ]
 then
     URL=$URL/
+fi
+
+#Checking if word list exists
+if [ ! -r $wordlist ]
+then
+    echo "Unable to read wordlist!"
+    exit 1
+fi
+
+#Checking if word list isn't empty
+if [ `wc -c $wordlist | sed s/$wordlist//g` -eq 0 ]
+then 
+    echo "Word list is empty."
+    exit 1
+else
+    echo "Word list has been found and is valid."
 fi
 
 printf "Trying to get token from: $URL$tok_gen_location with data: {\"username\":\"$username\",\"password\":\"$password\"}"
