Added check for output file

diff --git a/Script/JWT_Crawler_Config_File b/Script/JWT_Crawler_Config_File
--- a/Script/JWT_Crawler_Config_File
+++ b/Script/JWT_Crawler_Config_File
@@ -23,11 +23,21 @@ wordlist=""
 if [ $# -eq 2 -a "$1" == "-f" ]
 then
     printf "Parsing info from file: "$2"\n"
+    if [ ! -r $2 ]
+    then
+        printf "Couldn't read config file\n"
+        exit 1
+    fi
+
+    readarray -t confArray < $2
+
+
+
     #TODO: Parsing :3
-    exit
+    #exit
 else
     printf "Usage: JWT_Crawler_Config_File -f config_file\n"
-    exit
+    exit 1
 fi
 
 #URL sanitization
@@ -75,44 +85,58 @@ then
     fi
 fi
 
-#Checking if created and if writeable
-touch $outputFile
+if [ -n $outputFile ]
+then
+    #Checking if created and if writeable
+    touch $outputFile
 
-while [ ! -w $outputFile ]
-do 
-    echo "Output file is not writeable"
-    echo "What do you want to do?[e]xit, [r]ename:"
-    read answer
-
-    while [ ${answer:0:1} != 'r' -o ${answer:0:1} != 'e' ]
-    do
+    while [ ! -w $outputFile ]
+    do 
+        echo "Output file is not writeable"
         echo "What do you want to do?[e]xit, [r]ename:"
         read answer
-    done
-    if [ ${answer:0:1} == 'r']
-    then
-        read outputFile
-        touch $outputFile
-    fi
-    if [ ${answer:0:1} == 'e']
-    then
-        exit 1
-    fi
 
-done
+        while [ ${answer:0:1} != 'r' -o ${answer:0:1} != 'e' ]
+        do
+            echo "What do you want to do?[e]xit, [r]ename:"
+            read answer
+        done
+        if [ ${answer:0:1} == 'r']
+        then
+            read outputFile
+            touch $outputFile
+        fi
+        if [ ${answer:0:1} == 'e']
+        then
+            exit 1
+        fi
+
+    done
+
+fi
 
 printf "Trying to get token from: $URL$tok_gen_location with data: {\"username\":\"$username\",\"password\":\"$password\"}"
 TOKEN=$(curl -s -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' --data '{"username":$username,"password":$password}' $URL$tok_gen_location | jq -r)
 printf "\nToken should be "$TOKEN"\n"
 
-
-printf "Target URL is "$URL > $outputFile
+if [ -n $outputFile ]
+then
+    printf "Target URL is "$URL > $outputFile
+else
+    printf "Target URL is "$URL 
+fi
 #TODO: Recursive mode?
 for word in `cat "$wordlist"`
 do
-    printf "\nGetting $word" >> "$outputFile"
+    if [ -n $outputFile ]
+    then
+        printf "\nGetting $word" >> $outputFile
+    fi
     printf "\nGetting $word"
     curl -H 'Accept: application/json' -H "Authorization: Bearer ${TOKEN}" $URL$word >> $outputFile
 done
 
-printf "\nResult is in file $outputFile\n"
+if [ -n $outputFile ]
+then
+    printf "\nResult is in file $outputFile\n"
+fi
